import type {
  WorkspaceInfo, Product,
  Connector, AIModel, WorkspaceSettingsTab,
} from './types';

export const DEFAULT_WORKSPACE: WorkspaceInfo = {
  name: 'Wynta Workspace',
  slug: 'wynta-workspace',
  timezone: 'UTC',
  language: 'en',
  contactEmail: 'admin@wynta.com',
  description: 'Main workspace for the Wynta platform',
};

export const DEFAULT_PRODUCTS: Product[] = [
  {
    id: 'affiliate-platform',
    name: 'Affiliate Platform',
    description: 'Track, manage and scale affiliate partnerships with confidence.',
    icon: 'bar-chart-2',
    enabled: true,
    plan: 'Monthly Subscription',
    category: undefined,
    categoryColor: undefined,
    categoryBg: undefined,
  },
  {
    id: 'crm',
    name: 'CRM',
    description: 'Segment your players, run personalised multi-channel campaigns across email, SMS, push and in-app, and automate engagement flows triggered by real player behaviour.',
    icon: 'users',
    enabled: false,
    category: 'PLAYER RETENTION',
    categoryColor: '#1d4ed8',
    categoryBg: '#dbeafe',
  },
  {
    id: 'gamification',
    name: 'Gamification',
    description: 'Build a loyalty program players love: points, levels, missions and more, with configurable prize distribution.',
    icon: 'trophy',
    enabled: false,
    category: 'LOYALTY',
    categoryColor: '#16a34a',
    categoryBg: '#dcfce7',
  },
  {
    id: 'bonus-engine',
    name: 'Bonus Engine',
    description: 'Create and automate every bonus type with configurable wagering rules, multi-brand isolation, real-time triggers and built-in abuse prevention.',
    icon: 'gift',
    enabled: false,
    category: 'PROMOTIONS',
    categoryColor: '#d97706',
    categoryBg: '#fef3c7',
  },
  {
    id: 'web-analytics',
    name: 'Web Analytics',
    description: 'Track website visitor behaviour and conversion funnels.',
    icon: 'bar-chart-2',
    enabled: false,
    category: 'ANALYTICS',
    categoryColor: '#7c3aed',
    categoryBg: '#ede9fe',
  },
  {
    id: 'ab-testing',
    name: 'A/B Testing',
    description: 'Run controlled experiments to optimise campaigns and flows.',
    icon: 'git-branch',
    enabled: false,
    comingSoon: true,
    category: 'EXPERIMENTATION',
    categoryColor: '#d97706',
    categoryBg: '#fef3c7',
  },
  {
    id: 'ai-insights',
    name: 'AI Insights',
    description: 'AI-driven player behaviour predictions and anomaly detection.',
    icon: 'sparkles',
    enabled: false,
    plan: 'Pro',
    category: 'AI',
    categoryColor: '#0891b2',
    categoryBg: '#cffafe',
  },
];


export const DEFAULT_CONNECTORS: Connector[] = [
  { id: 'google-smtp',  name: 'Google',       category: 'Email', categoryDescription: 'Connect an email delivery provider for transactional and notification emails', icon: 'mail', iconBg: '#ffffff', status: 'disconnected', description: 'Gmail via SMTP / OAuth 2.0' },
  { id: 'mailgun',      name: 'Mailgun',      category: 'Email', icon: 'at-sign',  iconBg: '#fff3e0', status: 'disconnected', description: 'Transactional email API' },
  { id: 'sendgrid-em',  name: 'SendGrid',     category: 'Email', icon: 'send',     iconBg: '#dbeafe', status: 'disconnected', description: 'Cloud-based email delivery' },
  { id: 'ms-exchange',  name: 'MS Exchange',  category: 'Email', icon: 'repeat-2', iconBg: '#1e3a8a', status: 'disconnected', description: 'Microsoft Exchange SMTP relay' },
  { id: 'kafka',      name: 'Apache Kafka',     category: 'Infrastructure', categoryDescription: 'Core data infrastructure for event streaming and analytics storage', icon: 'activity',       iconBg: '#fef3c7', status: 'connected',    lastSync: '2 min ago',  description: 'Event streaming and message queue backbone' },
  { id: 'clickhouse', name: 'ClickHouse',        category: 'Infrastructure', icon: 'database',       iconBg: '#fce7f3', status: 'connected',    lastSync: '1 min ago',  description: 'Real-time analytics database for events' },
  { id: 'mongodb',    name: 'MongoDB',           category: 'Infrastructure', icon: 'hard-drive',     iconBg: '#d1fae5', status: 'connected',    lastSync: '5 min ago',  description: 'Document database for segments and campaigns' },
  { id: 'redis',      name: 'Redis',             category: 'Infrastructure', icon: 'server',         iconBg: '#fee2e2', status: 'connected',    lastSync: '30 sec ago', description: 'In-memory cache and rate limiting layer' },
  { id: 'fcm',        name: 'Firebase FCM',      category: 'Push',           categoryDescription: 'Connect push notification providers to send real-time messages to iOS and Android apps', icon: 'bell',           iconBg: '#fef3c7', status: 'disconnected',                         description: 'Push notifications via Firebase Cloud Messaging' },
  { id: 'sendgrid',   name: 'SendGrid',          category: 'Notifications',  icon: 'mail',           iconBg: '#dbeafe', status: 'disconnected',                         description: 'Transactional and marketing email delivery' },
  { id: 'twilio',     name: 'Twilio',            category: 'Notifications',  icon: 'phone',          iconBg: '#ede9fe', status: 'error',        lastSync: '1h ago',     description: 'SMS and voice communication service' },
  { id: 'whatsapp',   name: 'WhatsApp Business', category: 'Notifications',  icon: 'message-circle', iconBg: '#d1fae5', status: 'disconnected',                         description: 'WhatsApp Business API messaging channel' },
  { id: 'salesforce', name: 'Salesforce',        category: 'CRM',            categoryDescription: 'Sync player data with your existing CRM platforms', icon: 'briefcase',      iconBg: '#dbeafe', status: 'disconnected',                         description: 'Sync player data with Salesforce CRM' },
  { id: 'hubspot',    name: 'HubSpot',           category: 'CRM',            icon: 'users',          iconBg: '#fef3c7', status: 'disconnected',                         description: 'Sync segments and campaigns with HubSpot' },
  { id: 'webhook',    name: 'Custom Webhook',    category: 'Developer',      categoryDescription: 'Developer tools for data export and custom integrations', icon: 'link',           iconBg: '#f3f4f6', status: 'connected',    lastSync: '10 min ago', description: 'Stream real-time events to your endpoints' },
  { id: 's3',         name: 'Amazon S3',         category: 'Developer',      icon: 'archive',        iconBg: '#fef3c7', status: 'disconnected',                         description: 'Export bulk player data to your S3 bucket' },
];

export const DEFAULT_AI_MODELS: AIModel[] = [
  { id: '1', provider: 'ChatGPT', createdOn: '2026-06-07', isDefault: true  },
  { id: '2', provider: 'Gemini',  createdOn: '2026-06-08', isDefault: false },
];

export const TIMEZONES = [
  'Africa/Abidjan','Africa/Accra','Africa/Addis_Ababa','Africa/Algiers','Africa/Asmara','Africa/Asmera',
  'Africa/Bamako','Africa/Bangui','Africa/Banjul','Africa/Bissau','Africa/Blantyre','Africa/Brazzaville',
  'Africa/Bujumbura','Africa/Cairo','Africa/Casablanca','Africa/Ceuta','Africa/Conakry','Africa/Dakar',
  'Africa/Dar_es_Salaam','Africa/Djibouti','Africa/Douala','Africa/El_Aaiun','Africa/Freetown',
  'Africa/Gaborone','Africa/Harare','Africa/Johannesburg','Africa/Juba','Africa/Kampala','Africa/Khartoum',
  'Africa/Kigali','Africa/Kinshasa','Africa/Lagos','Africa/Libreville','Africa/Lome','Africa/Luanda',
  'Africa/Lubumbashi','Africa/Lusaka','Africa/Malabo','Africa/Maputo','Africa/Maseru','Africa/Mbabane',
  'Africa/Mogadishu','Africa/Monrovia','Africa/Nairobi','Africa/Ndjamena','Africa/Niamey','Africa/Nouakchott',
  'Africa/Ouagadougou','Africa/Porto-Novo','Africa/Sao_Tome','Africa/Timbuktu','Africa/Tripoli',
  'Africa/Tunis','Africa/Windhoek',
  'America/Adak','America/Anchorage','America/Anguilla','America/Antigua','America/Araguaina',
  'America/Argentina/Buenos_Aires','America/Argentina/Catamarca','America/Argentina/ComodRivadavia',
  'America/Argentina/Cordoba','America/Argentina/Jujuy','America/Argentina/La_Rioja',
  'America/Argentina/Mendoza','America/Argentina/Rio_Gallegos','America/Argentina/Salta',
  'America/Argentina/San_Juan','America/Argentina/San_Luis','America/Argentina/Tucuman',
  'America/Argentina/Ushuaia','America/Aruba','America/Asuncion','America/Atikokan','America/Atka',
  'America/Bahia','America/Bahia_Banderas','America/Barbados','America/Belem','America/Belize',
  'America/Blanc-Sablon','America/Boa_Vista','America/Bogota','America/Boise','America/Buenos_Aires',
  'America/Cambridge_Bay','America/Campo_Grande','America/Cancun','America/Caracas','America/Catamarca',
  'America/Cayenne','America/Cayman','America/Chicago','America/Chihuahua','America/Ciudad_Juarez',
  'America/Coral_Harbour','America/Cordoba','America/Costa_Rica','America/Coyhaique','America/Creston',
  'America/Cuiaba','America/Curacao','America/Danmarkshavn','America/Dawson','America/Dawson_Creek',
  'America/Denver','America/Detroit','America/Dominica','America/Edmonton','America/Eirunepe',
  'America/El_Salvador','America/Ensenada','America/Fort_Nelson','America/Fort_Wayne','America/Fortaleza',
  'America/Glace_Bay','America/Godthab','America/Goose_Bay','America/Grand_Turk','America/Grenada',
  'America/Guadeloupe','America/Guatemala','America/Guayaquil','America/Guyana','America/Halifax',
  'America/Havana','America/Hermosillo','America/Indiana/Indianapolis','America/Indiana/Knox',
  'America/Indiana/Marengo','America/Indiana/Petersburg','America/Indiana/Tell_City',
  'America/Indiana/Vevay','America/Indiana/Vincennes','America/Indiana/Winamac','America/Indianapolis',
  'America/Inuvik','America/Iqaluit','America/Jamaica','America/Jujuy','America/Juneau',
  'America/Kentucky/Louisville','America/Kentucky/Monticello','America/Knox_IN','America/Kralendijk',
  'America/La_Paz','America/Lima','America/Los_Angeles','America/Louisville','America/Lower_Princes',
  'America/Maceio','America/Managua','America/Manaus','America/Marigot','America/Martinique',
  'America/Matamoros','America/Mazatlan','America/Mendoza','America/Menominee','America/Merida',
  'America/Metlakatla','America/Mexico_City','America/Miquelon','America/Moncton','America/Monterrey',
  'America/Montevideo','America/Montreal','America/Montserrat','America/Nassau','America/New_York',
  'America/Nipigon','America/Nome','America/Noronha','America/North_Dakota/Beulah',
  'America/North_Dakota/Center','America/North_Dakota/New_Salem','America/Nuuk','America/Ojinaga',
  'America/Panama','America/Pangnirtung','America/Paramaribo','America/Phoenix','America/Port-au-Prince',
  'America/Port_of_Spain','America/Porto_Acre','America/Porto_Velho','America/Puerto_Rico',
  'America/Punta_Arenas','America/Rainy_River','America/Rankin_Inlet','America/Recife','America/Regina',
  'America/Resolute','America/Rio_Branco','America/Rosario','America/Santa_Isabel','America/Santarem',
  'America/Santiago','America/Santo_Domingo','America/Sao_Paulo','America/Scoresbysund',
  'America/Shiprock','America/Sitka','America/St_Barthelemy','America/St_Johns','America/St_Kitts',
  'America/St_Lucia','America/St_Thomas','America/St_Vincent','America/Swift_Current',
  'America/Tegucigalpa','America/Thule','America/Thunder_Bay','America/Tijuana','America/Toronto',
  'America/Tortola','America/Vancouver','America/Virgin','America/Whitehorse','America/Winnipeg',
  'America/Yakutat','America/Yellowknife',
  'Antarctica/Casey','Antarctica/Davis','Antarctica/DumontDUrville','Antarctica/Macquarie',
  'Antarctica/Mawson','Antarctica/McMurdo','Antarctica/Palmer','Antarctica/Rothera',
  'Antarctica/South_Pole','Antarctica/Syowa','Antarctica/Troll','Antarctica/Vostok',
  'Arctic/Longyearbyen',
  'Asia/Aden','Asia/Almaty','Asia/Amman','Asia/Anadyr','Asia/Aqtau','Asia/Aqtobe','Asia/Ashgabat',
  'Asia/Ashkhabad','Asia/Atyrau','Asia/Baghdad','Asia/Bahrain','Asia/Baku','Asia/Bangkok',
  'Asia/Barnaul','Asia/Beirut','Asia/Bishkek','Asia/Brunei','Asia/Calcutta','Asia/Chita',
  'Asia/Choibalsan','Asia/Chongqing','Asia/Chungking','Asia/Colombo','Asia/Dacca','Asia/Damascus',
  'Asia/Dhaka','Asia/Dili','Asia/Dubai','Asia/Dushanbe','Asia/Famagusta','Asia/Gaza','Asia/Harbin',
  'Asia/Hebron','Asia/Ho_Chi_Minh','Asia/Hong_Kong','Asia/Hovd','Asia/Irkutsk','Asia/Istanbul',
  'Asia/Jakarta','Asia/Jayapura','Asia/Jerusalem','Asia/Kabul','Asia/Kamchatka','Asia/Karachi',
  'Asia/Kashgar','Asia/Kathmandu','Asia/Katmandu','Asia/Khandyga','Asia/Kolkata','Asia/Krasnoyarsk',
  'Asia/Kuala_Lumpur','Asia/Kuching','Asia/Kuwait','Asia/Macao','Asia/Macau','Asia/Magadan',
  'Asia/Makassar','Asia/Manila','Asia/Muscat','Asia/Nicosia','Asia/Novokuznetsk','Asia/Novosibirsk',
  'Asia/Omsk','Asia/Oral','Asia/Phnom_Penh','Asia/Pontianak','Asia/Pyongyang','Asia/Qatar',
  'Asia/Qostanay','Asia/Qyzylorda','Asia/Rangoon','Asia/Riyadh','Asia/Saigon','Asia/Sakhalin',
  'Asia/Samarkand','Asia/Seoul','Asia/Shanghai','Asia/Singapore','Asia/Srednekolymsk','Asia/Taipei',
  'Asia/Tashkent','Asia/Tbilisi','Asia/Tehran','Asia/Tel_Aviv','Asia/Thimbu','Asia/Thimphu',
  'Asia/Tokyo','Asia/Tomsk','Asia/Ujung_Pandang','Asia/Ulaanbaatar','Asia/Ulan_Bator','Asia/Urumqi',
  'Asia/Ust-Nera','Asia/Vientiane','Asia/Vladivostok','Asia/Yakutsk','Asia/Yangon',
  'Asia/Yekaterinburg','Asia/Yerevan',
  'Atlantic/Azores','Atlantic/Bermuda','Atlantic/Canary','Atlantic/Cape_Verde','Atlantic/Faeroe',
  'Atlantic/Faroe','Atlantic/Jan_Mayen','Atlantic/Madeira','Atlantic/Reykjavik',
  'Atlantic/South_Georgia','Atlantic/St_Helena','Atlantic/Stanley',
  'Australia/ACT','Australia/Adelaide','Australia/Brisbane','Australia/Broken_Hill',
  'Australia/Canberra','Australia/Currie','Australia/Darwin','Australia/Eucla','Australia/Hobart',
  'Australia/LHI','Australia/Lindeman','Australia/Lord_Howe','Australia/Melbourne','Australia/NSW',
  'Australia/North','Australia/Perth','Australia/Queensland','Australia/South','Australia/Sydney',
  'Australia/Tasmania','Australia/Victoria','Australia/West','Australia/Yancowinna',
  'Brazil/Acre','Brazil/DeNoronha','Brazil/East','Brazil/West',
  'CET','CST6CDT',
  'Canada/Atlantic','Canada/Central','Canada/Eastern','Canada/Mountain','Canada/Newfoundland',
  'Canada/Pacific','Canada/Saskatchewan','Canada/Yukon',
  'Chile/Continental','Chile/EasterIsland',
  'Cuba','EET','EST','EST5EDT','Egypt','Eire',
  'Etc/GMT','Etc/GMT+0','Etc/GMT+1','Etc/GMT+10','Etc/GMT+11','Etc/GMT+12','Etc/GMT+2','Etc/GMT+3',
  'Etc/GMT+4','Etc/GMT+5','Etc/GMT+6','Etc/GMT+7','Etc/GMT+8','Etc/GMT+9','Etc/GMT-0','Etc/GMT-1',
  'Etc/GMT-10','Etc/GMT-11','Etc/GMT-12','Etc/GMT-13','Etc/GMT-14','Etc/GMT-2','Etc/GMT-3',
  'Etc/GMT-4','Etc/GMT-5','Etc/GMT-6','Etc/GMT-7','Etc/GMT-8','Etc/GMT-9','Etc/GMT0',
  'Etc/Greenwich','Etc/UCT','Etc/UTC','Etc/Universal','Etc/Zulu',
  'Europe/Amsterdam','Europe/Andorra','Europe/Astrakhan','Europe/Athens','Europe/Belfast',
  'Europe/Belgrade','Europe/Berlin','Europe/Bratislava','Europe/Brussels','Europe/Bucharest',
  'Europe/Budapest','Europe/Busingen','Europe/Chisinau','Europe/Copenhagen','Europe/Dublin',
  'Europe/Gibraltar','Europe/Guernsey','Europe/Helsinki','Europe/Isle_of_Man','Europe/Istanbul',
  'Europe/Jersey','Europe/Kaliningrad','Europe/Kiev','Europe/Kirov','Europe/Kyiv','Europe/Lisbon',
  'Europe/Ljubljana','Europe/London','Europe/Luxembourg','Europe/Madrid','Europe/Malta',
  'Europe/Mariehamn','Europe/Minsk','Europe/Monaco','Europe/Moscow','Europe/Nicosia','Europe/Oslo',
  'Europe/Paris','Europe/Podgorica','Europe/Prague','Europe/Riga','Europe/Rome','Europe/Samara',
  'Europe/San_Marino','Europe/Sarajevo','Europe/Saratov','Europe/Simferopol','Europe/Skopje',
  'Europe/Sofia','Europe/Stockholm','Europe/Tallinn','Europe/Tirane','Europe/Tiraspol',
  'Europe/Ulyanovsk','Europe/Uzhgorod','Europe/Vaduz','Europe/Vatican','Europe/Vienna',
  'Europe/Vilnius','Europe/Volgograd','Europe/Warsaw','Europe/Zagreb','Europe/Zaporozhye',
  'Europe/Zurich',
  'GMT','GMT+0','GMT-0','GMT0','Greenwich','HST','Hongkong','Iceland',
  'Indian/Antananarivo','Indian/Chagos','Indian/Christmas','Indian/Cocos','Indian/Comoro',
  'Indian/Kerguelen','Indian/Mahe','Indian/Maldives','Indian/Mauritius','Indian/Mayotte',
  'Indian/Reunion',
  'Iran','Israel','Jamaica','Japan','Kwajalein','Libya','MET','MST','MST7MDT',
  'Mexico/BajaNorte','Mexico/BajaSur','Mexico/General',
  'NZ','NZ-CHAT','Navajo','PRC','PST8PDT',
  'Pacific/Apia','Pacific/Auckland','Pacific/Bougainville','Pacific/Chatham','Pacific/Chuuk',
  'Pacific/Easter','Pacific/Efate','Pacific/Enderbury','Pacific/Fakaofo','Pacific/Fiji',
  'Pacific/Funafuti','Pacific/Galapagos','Pacific/Gambier','Pacific/Guadalcanal','Pacific/Guam',
  'Pacific/Honolulu','Pacific/Johnston','Pacific/Kanton','Pacific/Kiritimati','Pacific/Kosrae',
  'Pacific/Kwajalein','Pacific/Majuro','Pacific/Marquesas','Pacific/Midway','Pacific/Nauru',
  'Pacific/Niue','Pacific/Norfolk','Pacific/Noumea','Pacific/Pago_Pago','Pacific/Palau',
  'Pacific/Pitcairn','Pacific/Pohnpei','Pacific/Port_Moresby','Pacific/Rarotonga','Pacific/Saipan',
  'Pacific/Samoa','Pacific/Tahiti','Pacific/Tarawa','Pacific/Tongatapu','Pacific/Truk','Pacific/Wake',
  'Pacific/Wallis','Pacific/Yap',
  'Poland','Portugal','ROC','ROK','Singapore','Turkey','UCT',
  'US/Alaska','US/Aleutian','US/Arizona','US/Central','US/East-Indiana','US/Eastern','US/Hawaii',
  'US/Indiana-Starke','US/Michigan','US/Mountain','US/Pacific','US/Samoa',
  'UTC','Universal','W-SU','WET','Zulu',
].map(tz => ({ value: tz, label: tz }));

export const LANGUAGES = [
  { value: 'en', label: 'English'    },
  { value: 'hi', label: 'Hindi'      },
  { value: 'ar', label: 'Arabic'     },
  { value: 'de', label: 'German'     },
  { value: 'fr', label: 'French'     },
  { value: 'es', label: 'Spanish'    },
  { value: 'pt', label: 'Portuguese' },
  { value: 'ja', label: 'Japanese'   },
];

export const AI_PROVIDERS = [
  { id: 'anthropic', label: 'Anthropic', models: ['claude-sonnet-4-6', 'claude-haiku-4-5-20251001', 'claude-opus-4-8'] },
  { id: 'openai',    label: 'OpenAI',    models: ['gpt-4o', 'gpt-4o-mini', 'gpt-4-turbo'] },
  { id: 'google',    label: 'Google',    models: ['gemini-2.0-flash', 'gemini-1.5-pro', 'gemini-1.5-flash'] },
  { id: 'custom',    label: 'Custom',    models: ['custom-endpoint'] },
];

export const DEFAULT_TABS: WorkspaceSettingsTab[] = [
  { id: 'general',    label: 'General',    icon: 'settings' },
  { id: 'products',   label: 'Products',   icon: 'box'      },
  { id: 'users',      label: 'Users',      icon: 'users'    },
  { id: 'connectors', label: 'Connectors', icon: 'plug'     },
  { id: 'ai-model',   label: 'AI Model',        icon: 'sparkles'     },
];
